config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
  root to: 'articles#index'

  get 'about', to: 'pages#about', as: :about
  get 'about/edit', to: 'pages#aboutedit', as: :edit_about
  patch 'about', to: 'pages#update', as: :update_about
  get 'articles/:id/htmledit', to: 'articles#htmledit', as: :htmledit_article
  get 'dispatches/:id/htmledit', to: 'dispatches#htmledit', as: :htmledit_dispatch
  get 'profiles/:id/htmledit', to: 'profiles#htmledit', as: :htmledit_profile
  get 'opinions/:id/htmledit', to: 'opinions#htmledit', as: :htmledit_opinion
  get 'updates/:id/htmledit', to: 'updates#htmledit', as: :htmledit_update
  get 'gathering', to: 'pages#gathering', as: :gathering
  get 'gathering?edit', to: 'pages#gathering', as: :edit_gathering
  get 'emergepodcast', to: 'podcasts#emergepodcast', as: :emergepodcast
  get 'imprint', to: 'pages#imprint', as: :imprint
  get 'imprint/edit', to: 'pages#imprintedit', as: :edit_imprint
  get 'gdpr', to: 'pages#gdpr', as: :gdpr

  get 'articles/:id/publish!', to: 'articles#publish!', as: 'publish_article'
  get 'articles/:id/delete', to: 'articles#delete', as: 'delete_article'

  get 'pins/:id/publish!', to: 'pins#publish!', as: 'publish_pin'
  get 'pins/:id/delete', to: 'pins#delete', as: 'delete_pin'

  resources :articles, :contributors, :photographers, :profiles, :opinions, :photos, :images, :updates, :pins, :videos, :podcasts, :events, :spaces, :dispatches

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/space.rb
class Space < ApplicationRecord
  geocoded_by :location
  after_validation :geocode
end

app/controllers/spaces_controller.rb
class SpacesController < ArticlesController
  before_action :set_category
  before_action :authenticate_user!

  def index
    @page = 'index'
    @pins = Pin.space.published_not_deleted
    @pins = Pin.space.not_deleted if user_signed_in?

    @event_types = @pins.pluck(:event_type).uniq
    @regions = @pins.pluck(:region).uniq

    @pins = @pins.event_type(params[:event_type]) if params[:event_type].present?
    @pins = @pins.region(params[:region]) if params[:region].present?

    @pagy, @pins = pagy_array(sort_pins, items: 7)
  end

  def show
    @page = 'grey'
    @pin = Pin.find(params[:id])
  end

  def new
    @page = 'grey'
    @pin = Pin.new
  end

  def create
    @pin = Pin.new(space_params)
    if params[:commit] == 'Publish' || params[:commit] == 'Unpublish'
      @pin.published = !@pin.published
      @pin.published_at = Time.now
    end
    @pin.save
    redirect_to space_path(@pin)
  end

  def edit
    @pin = Pin.find(params[:id])
    @event = Pin.find(params[:id])
  end

  def update
    @pin = Pin.find(params[:id])
    @pin.update(space_params)
    if params[:commit] == 'Publish' || params[:commit] == 'Unpublish'
      @pin.published = !@pin.published
      @pin.published_at = Time.now
    end
    @pin.save
    redirect_to space_path(@pin)
  end

  private

  def set_category
    @category = 'space'
  end

  def space_params
    params.require(:pin).permit(:name, :category, :event_type, :location, :region, :phone, :date, :end_date, :address, :url, :description, :published, :photo)
  end

  def sort_pins
    @pins.each { |pin| pin.published_at = Time.now if pin.published_at == nil }
    @pins.sort_by { |pin| pin.published_at }.reverse
  end
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/edit.html.erb
<div class="opinion-container">
  <%= form_for @pin, url: {action: "update"}, html: {class: "article_form"} do |f| %>
    <%= f.hidden_field :category, value: @category %>
    <h1>Space</h1>
    <p><%= f.text_area :name, placeholder: "Space name" %></p>
    <p><%= f.text_area :tag, placeholder: "Space tag"%></p>
    <p><%= f.text_area :event_type, placeholder: "Type of space" %></p>
    <p><%= f.text_area :location, placeholder: 'Location' %></p>
    <p><%= f.text_area :region, placeholder: 'Region' %></p>
    <p><%= f.text_area :phone, placeholder: 'Phone Number' %></p>
    <p><%= f.text_area :address, placeholder: 'Address' %></p>
    <p><%= f.text_field :photo, placeholder: 'preview photo url', :prompt => 'Select' %></p>
    <p><%= f.text_area :url, placeholder: 'Space url' %></p>
    <p><%= f.trix_editor :description, placeholder: 'Description' %></p>
    <p><%= f.select :published, [true, false], :include_blank => 'publish?' %></p>
    <%= f.submit 'Save' %>
    <% if @pin.published %>
      <%= f.submit 'Unpublish' %>
    <% else %>
      <%= f.submit 'Publish' %>
    <% end %>
    </div>
  <% end %>
</div>

app/views/spaces/index.html.erb
<div class="grid-container">
  <div class="interviews_grid">
    <h1 class="page-head">Spaces</h2>
    <h2 class="page-subhead">Discover hubs of the emerging new culture.</h2>
    <div class="event-filters">
      <%= form_tag spaces_path, method: :get do %>
        <%= select_tag(:event_type, options_for_select(@event_types), prompt: 'Category') %>
        <%= select_tag(:region, options_for_select(@regions), prompt: 'Location') %>
        <div class="event-filter-buttons-container">
          <%= submit_tag("Search", id: 'button-clear') %>
          <%= link_to 'See all' , spaces_path, id: 'button-clear' %>
        </div>
      <% end %>
    </div>

    <div class="grid_flex">
      <% @pins.each do |pin| %>
        <%= render 'shared/eventcard', pin: pin %>
      <% end %>
      <div class="card-container card-contribute">
        <%= link_to 'https://docs.google.com/forms/d/e/1FAIpQLSe0m7OSMeBkSRpVtGYi2rAFqROHK6so2hqQlylXe_VLxuCwlQ/viewform', target: "_blank" do %>
          <div class="card">
            <div class="card-plus">+</div>
            <h2 class=card-headline>Do you have an event to share with the emerge community?</h2>
          </div>
        <% end %>
      </div>
    </div>
    <div class="pagy-container">
      <%== paginate(@pagy) %>
    </div>
  </div>
</div>

app/views/spaces/new.html.erb
<div class="opinion-container">
  <%= form_for @pin, url: {action: "create"}, html: {class: "article_form"} do |f| %>
    <%= f.hidden_field :category, value: @category %>
    <h1>Space</h1>
    <p><%= f.text_area :name, placeholder: "Space name", required: true %></p>
    <p><%= f.text_area :tag, placeholder: "Space tag", required: true %></p>
    <p><%= f.text_area :event_type, placeholder: "Type of space", required: true %></p>
    <p><%= f.text_area :location, placeholder: 'Location', required: true %></p>
    <p><%= f.text_area :region, placeholder: 'Region', required: true %></p>
    <p><%= f.text_area :phone, placeholder: 'Phone Number' %></p>
    <p><%= f.text_area :address, placeholder: 'Address', required: true %></p>
    <p><%= f.text_field :photo, placeholder: 'preview photo url', :prompt => 'Select', required: true %></p>
    <p><%= f.text_area :url, placeholder: 'Space url' %></p>
    <p><%= f.trix_editor :description, placeholder: 'Description' %></p>
    <p><%= f.select :published, [true, false], :include_blank => 'publish?' %></p>
    <%= f.submit 'Save' %>
    <% if @pin.published %>
      <%= f.submit 'Unpublish' %>
    <% else %>
      <%= f.submit 'Publish' %>
    <% end %>
    </div>
  <% end %>
</div>

app/views/spaces/show.html.erb
<% content_for :meta_title, "#{@pin.name} - #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, strip_tags(@pin.description) %>
<% content_for :meta_image, @pin.photo.sub('upload/', 'upload/c_fill,h_675,w_1200/') %>

<div class="event-header-photo" style="background-image: url('<%= @pin.photo %>')">
  <div></div>
</div>
  <div class="event-head-card">
    <h1 class="profile-headline upcase"><%= @pin.name %></h1>
    <p><%= @pin.address %>

    </p>
    <div class=" "><%= @pin.phone %></div>
    <%= link_to @pin.url, @pin.url, target: "_blank", class: 'event-link' %>
  </div>

<div class="event-container">
  <div class="event-body"><%= @pin.description.html_safe
    %>
  </div>
</div>

<script>
  var imgs = document.querySelectorAll('.event-body img');
  var divs = document.querySelectorAll('.event-body div');
  var videos = document.querySelectorAll('.event-body video');
  console.log(imgs);
  console.log(divs);

  [].forEach.call(divs, function(div) {
    div.classList.add("body");
  });

  [].forEach.call(imgs, function(img) {
    img.closest("div").classList.remove("body");
    img.closest("div").classList.add("wide");
  });

  [].forEach.call(videos, function(video) {
    video.closest("div").classList.remove("body");
    video.closest("div").classList.add("video");
  });
</script>