config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
  root to: 'articles#index'

  get 'about', to: 'pages#about', as: :about
  get 'about/edit', to: 'pages#aboutedit', as: :edit_about
  patch 'about', to: 'pages#update', as: :update_about
  get 'articles/:id/htmledit', to: 'articles#htmledit', as: :htmledit_article
  get 'dispatches/:id/htmledit', to: 'dispatches#htmledit', as: :htmledit_dispatch
  get 'profiles/:id/htmledit', to: 'profiles#htmledit', as: :htmledit_profile
  get 'opinions/:id/htmledit', to: 'opinions#htmledit', as: :htmledit_opinion
  get 'updates/:id/htmledit', to: 'updates#htmledit', as: :htmledit_update
  get 'gathering', to: 'pages#gathering', as: :gathering
  get 'gathering?edit', to: 'pages#gathering', as: :edit_gathering
  get 'emergepodcast', to: 'podcasts#emergepodcast', as: :emergepodcast
  get 'imprint', to: 'pages#imprint', as: :imprint
  get 'imprint/edit', to: 'pages#imprintedit', as: :edit_imprint
  get 'gdpr', to: 'pages#gdpr', as: :gdpr

  get 'articles/:id/publish!', to: 'articles#publish!', as: 'publish_article'
  get 'articles/:id/delete', to: 'articles#delete', as: 'delete_article'

  get 'pins/:id/publish!', to: 'pins#publish!', as: 'publish_pin'
  get 'pins/:id/delete', to: 'pins#delete', as: 'delete_pin'

  resources :articles, :contributors, :photographers, :profiles, :opinions, :photos, :images, :updates, :pins, :videos, :podcasts, :events, :spaces, :dispatches

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :contributor, optional: true
  belongs_to :photographer, optional: true
  extend FriendlyId
  friendly_id :headline, use: [:finders, :slugged]
  validates_presence_of :headline, :slug

  validates :category, inclusion: { in: %w(insight people video podcast journal imprint about gathering) }

  include PgSearch
  multisearchable against: [ :person, :headline, :seo_title, :subhead, :meta, :tag, :body ]

  scope :published, -> { where(published: true)}
  scope :not_published, -> { where(published: false)}
  scope :not_deleted, -> { where(deleted: false)}
  scope :published_not_deleted, -> { published.not_deleted }

  scope :journal, -> { where(category: 'journal')}
  scope :people, -> { where(category: 'people')}
  scope :insight, -> { where(category: 'insight')}
  scope :video, -> { where(category: 'video')}
  scope :podcast, -> { where(category: 'podcast')}
  scope :not_update, -> { where.not(category: 'update')}
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  has_many :articles
end

app/models/event.rb
class Event < ApplicationRecord
  geocoded_by :location
  after_validation :geocode

  default_scope { order(published_at: :desc) }
  scope :category, -> (category) { where category: category }
  scope :event_type, -> (event_type) { where event_type: event_type}
  scope :location, -> (location) { where location: location }
  scope :month, -> (date) { where date: month }

  class Product < ActiveRecord::Base
    scope :status, -> (status) { where status: status }
    scope :location, -> (location_id) { where location_id: location_id }
    scope :starts_with, -> (name) { where("name like ?", "#{name}%")}
  end
end

app/models/medium.rb
class Medium < ApplicationRecord
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  include ImageUploader::Attachment(:image) # adds an `image` virtual attribute
end

app/models/photographer.rb
class Photographer < ApplicationRecord
end

app/models/pin.rb
class Pin < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:finders, :slugged]
  validates_presence_of :name, :slug

  geocoded_by :location
  after_validation :geocode

  include PgSearch
  multisearchable against: [ :name, :category, :tag, :classification, :event_type, :location, :address, :description ]

  default_scope { order(published_at: :desc) }

  scope :published, -> { where(published: true) }
  scope :not_deleted, -> { where(deleted: false) }
  scope :published_not_deleted, -> { published.not_deleted }
  scope :since_today, -> { where('date >= ? or end_date >= ?', Date.today, Date.today) }

  scope :space, -> {where(category: 'space')}
  scope :event, -> {where(category: 'event')}

  scope :event_type, -> (type) {where(event_type: type)}
  scope :region, -> (region) {where(region: region)}
  scope :tag, -> (tag) {where(tag: tag)}
end

app/models/podcast.rb
class Podcast < Medium
end

app/models/space.rb
class Space < ApplicationRecord
  geocoded_by :location
  after_validation :geocode
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < Medium
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def filter_and_sort_articles(include_category, include_priority, tag: nil )
    #logged in or logged out
    articles = user_signed_in? ? Article.not_deleted : Article.published_not_deleted
    #filter by allowed category/ies
    #filter by allowed priority
    priority = include_priority
    articles = articles.where(category: include_category, priority: priority)
    articles = articles.where("lower(tag) = ?", tag.downcase) if tag
    #calc 'age' w/ priority
    #sort by age
    sort_by_priority(articles)
  end

  def sort_by_priority(articles)
    articles.each { |article| article.published_at = Time.now if article.published_at == nil }
    articles.each { |article| article.age = Time.now - article.published_at }
    articles.each do |article|
      case article.priority
      when 3
        article.age = article.age * 4
      when 4
        article.age = article.age * 16
      when 5
        article.age = article.age * 32
      end
    end
    articles.sort_by &:age
  end

  def process_body(article_body)
    body = article_body
        .gsub(/&lt;/, '<')
        .gsub(/&gt;/, '>')

    sanitize body,
      tags: %w(strong em b i p code pre tt samp kbd var sub
        sup dfn cite big small address hr div span h1 h2 h3 h4 h5 h6 ul ol li dl dt dd abbr
        acronym a img blockquote del ins video source figcaption figure br iframe),
      attributes: %w(href src width height alt cite datetime title class name xml:lang abbr
        type autoplay loop data-trix-attachment data-trix-content-type)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/media_helper.rb
module MediaHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/images/new.html.erb
<%= form_for Image.new, url: {action: "create"} do |f| %>
  <%= f.file_field :image, required: true %>
  <%= f.submit %>
<% end %>

app/views/images/show.html.erb
<%# image_url = cloudinary(@image.image_url) %>
<%#= image_tag image_url %>

<%= image_tag s3_url(@image) %>
<%= s3_url(@image) %>

app/views/shared/_card.html.erb
<% category_tag ||= current_page?(controller: 'articles', action: 'index') %>

<div class="card-container">
  <% if user_signed_in? %>
    <div class="logged-in-card">
      <h3 class="admin">
        <%= link_to('edit', edit_article_path(article)) %>
      </h3>
      <h3>
        <%= link_to('unpublish', publish_article_path(article)) if article.published %>
        <%= link_to('publish', publish_article_path(article)) unless article.published %>
      </h3>
      <h3>
        <%= link_to('delete', delete_article_path(article)) %>
      </h3>
    </div>
  <% end %>

  <%= link_to card_route(article), target: external_link(article) do %>
    <%= content_tag :div, class: published?(article) do %>
      <% article.category == 'podcast' ? width = 400 : width = 720 %>
      <%= content_tag :div, class: podcast_img?(article),
                      style: "background-image:url('#{cloudinary_to_s3_url(article.photo)}')" do %>
        <% if category_tag %>
          <div class="card-tag-left category"><%= article.category %></div>
        <% end %>
        <% if article.tag.present? %>
          <div class="card-tag tag"><%= article.tag %></div>
        <% end %>
      <% end %>
      <div class="card-text small">
        <h3 class="card-headline">
          <%= article.headline %>
        </h3>
        <h3 class="card-contributor">
          <%= "#{article.contributor.name}" if article.category == "insight" && article.contributor.present? %>
        </h3>
        <h4 class="card-subhead"><%= article.subhead %></h4>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_contributecard.html.erb
<div class="card-container card-contribute">
  <%= link_to 'https://docs.google.com/forms/d/1ciwqXm0_iPkTScYDuscZPMF_wqBC6araTf3T6ThcP84/edit' do %>
    <div class="card-media">
      <div class="card-plus">+</div>
      <div class=card-headline>Do you have a video to share with the emerge community?</div>
    </div>
  <% end %>
</div>

app/views/shared/_contributor.html.erb
<% if @article.present? %>
  <% if @article.contributor.present? %>
    <div class="contributor-container">
      <%= image_tag @article.contributor&.photo, class: "contributor-image" %>
      <div class="contributor-text-container">
        <% if user_signed_in? && @article.contributor %>
          <%= link_to('edit contributor', edit_contributor_path(@article.contributor)) %>
        <% end %>

        <div class="contributor-text-header">
          Words by <span class="contributor-name upcase"><%= @article.contributor&.name %></span>
        </div>
        <div class="flex-start">
          <% if @article.contributor&.twitter.present? %>
            <%= link_to "https://twitter.com/#{@article.contributor&.twitter}", target: "_blank", rel: "nofollow" do %>
              <i class="social fab fa-twitter"></i>
            <% end %>
          <% end %>
          <% if @article.contributor&.instagram.present? %>
            <%= link_to "https://www.instagram.com/#{@article.contributor&.instagram}/", target: "_blank", rel: "nofollow" do %>
              <i class="social fab fa-instagram"></i>
            <% end %>
          <% end %>
          <% if @article.contributor&.linked_in.present? %>
            <%= link_to @article.contributor.linked_in, target: "_blank", rel: "nofollow" do %>
              <i class="social fab fa-linkedin"></i>
            <% end %>
          <% end %>
          <% if @article.contributor&.website.present? %>
            <%= link_to @article.contributor.website, target: "_blank", rel: "nofollow" do %>
              <i class="social fas fa-link"></i>
            <% end %>
          <% end %>
        </div>
        <%= @article.contributor&.bio.html_safe %>
      </div>
    </div>
  <% end %>
  </div>
  <% if @article.photographer.present? %>
    <div class="contributor-container">
      <div class="contributor-text-container-left">
        <% if user_signed_in? %>
          <%= link_to('edit photographer', edit_photographer_path(@article.photographer)) %>
        <% end %>
        <div class="contributor-text-header">Photos by
          <span class="contributor-name upcase"><%= @article.photographer.name %></span>
        </div>
        <div class="flex-start">
          <% if @article.photographer.twitter.present? %>
            <%= link_to "https://twitter.com/#{@article.photographer.twitter}", target: "_blank", rel: "nofollow" do %>
              <i class="social fab fa-twitter"></i>
            <% end %>
          <% end %>
          <% if @article.photographer.instagram.present? %>
            <%= link_to "https://www.instagram.com/#{@article.photographer.instagram}/", target: "_blank", rel: "nofollow" do %>
              <i class="social fab fa-instagram"></i>
            <% end %>
          <% end %>
          <% if @article.photographer.website.present? %>
            <%= link_to @article.photographer.website, target: "_blank", rel: "nofollow" do %>
              <i class="social fas fa-link"></i>
            <% end %>
          <% end %>
        </div>
        <%= @article.photographer.bio %>
      </div>
      <%= image_tag @article.photographer.photo, class: "contributor-image" %>
    </div>
  <% end %>
<% end %>

app/views/shared/_eventcard.html.erb
<div class="card-container">
  <% if user_signed_in? %>
    <div class="logged-in-card">
      <h3 class="admin">
        <%= link_to('edit', edit_pin_path(pin)) %>
      </h3>
      <h3>
        <%= link_to('unpublish', publish_pin_path(pin)) if pin.published %>
        <%= link_to('publish', publish_pin_path(pin)) unless pin.published %>
      </h3>
      <h3>
        <%= link_to('delete', delete_pin_path(pin)) %>
      </h3>
    </div>
  <% end %>

  <%= link_to pin_path(pin) do %>
    <%= content_tag :div, class: pin_published?(pin) do %>
      <% unless pin.photo.nil? %>
        <div class="card-img" style=<%="background-image:url('#{cloudinary_to_s3_url(pin.photo)}')"%>>
          <% if pin.tag.present? %>
            <div class="card-tag-left category"><%= pin.tag %></div>
          <% end %>
          <% if pin.event_type.present? %>
            <div class="card-tag tag"><%= pin.event_type %></div>
          <% end %>
        </div>
      <% end %>
      <div class="card-text small">
        <h3 class="card-headline">
          <%= pin.name %>
        </h3>
        <h4 class="card-date"><%= "#{pin.date.strftime("%-d.%-m.%Y")}" unless pin.date.nil? %> <%= " - #{pin.end_date.strftime("%-d.%-m.%Y")}" unless pin.end_date.nil? %></h4>
        <h4 class="card-subhead"><%= pin.location %></h4>
        <h4 class="card-subhead"><%= sanitize pin.description.truncate(150, separator: '</div>'), tags: %w(strong em) %></h4>
      </div>
    <% end %>
  <% end %>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <% if notice.present? %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
  <% end %>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_gdpr.html.erb
<% if cookies && cookies['gdpr.cookie_consent.ok'] != 'true' %>
  <div class="gdpr__cookie_consent js-gdpr__cookie_consent">
    <div class="gdpr__cookie_consent__text">
      <%= 'By navigating on this website, you agree to our use of cookies to personalize certain website features and to measure the audience and use of this website.' %>
    </div>
    <div class="gdpr__cookie_consent__buttons">
      <button class="gdpr__cookie_consent__buttons__ok js-gdpr__cookie_consent__buttons__ok"> <%= 'OK' %></button>
    </div>
  </div>
<% end %>

app/views/shared/_homecard.html.erb
<div class="home-card-container">
  <%= link_to edit_article_path(article) do %>
    <% if user_signed_in? %>
    <div class="logged-in-card">
      <h3 class="logged-in-left admin">edit</h3>
      <% if article.published %>
      <h3 class="admin">published</h3>
      <% else %>
      <h3 class="admin">draft</h3>
      <% end %>
    </div>
    <% end %>
  <% end %>

  <%= link_to article_path(article) do %>
    <%= content_tag :div, class: published?(article) do %>
      <div class="card-img" style="background-image: url('<%= article.photo %>')">
        <div class="card-tag tag"><%= article.tag %></div>
      </div>
      <div class="card-text small">
        <div class="card-headline">
          <%= "#{article.contributor&.name}: " if article.category == "opinion" %><%= article.headline %>
        </div>
        <div class="card-subhead"><%= article.subhead %></div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_logged-in.html.erb
<div class="logged-in-container">

  <!-- Left Navigation -->
  <div class="logged-in-left admin">
    <%= current_user.email %>
  </div>

  <!-- right Navigation -->
  <div class="logged-in-right">
    <%= link_to "Edit", edit_article_path(@article), class: "admin white" if show_view? %>
    <%= link_to "Edit", edit_contributor_path(@contributor), class: "admin white" if contributor_view? %>
    <%= link_to "Edit", edit_photographer_path(@photographer), class: "admin white" if photographer_view? %>

    <% case action_name %>
    <% when 'about' %>
      <div class="flex-end">
        <%= link_to '-Edit', edit_about_path, class: 'logged-in-button' %>
        <%= link_to destroy_user_session_path, method: :delete, class: "logged-in-button" do %>
          <i class="fas fa-sign-out-alt"></i>
        <% end %>
      </div>
    <% when 'imprint' %>
      <div class="flex-end">
        <%= link_to '-Edit', edit_imprint_path, class: 'logged-in-button' %>
        <%= link_to destroy_user_session_path, method: :delete, class: "logged-in-button" do %>
          <i class="fas fa-sign-out-alt"></i>
        <% end %>
      </div>
    <% when 'gathering' %>
        <%= link_to '-Edit', edit_gathering_path, class: 'logged-in-button' %>
        <%= link_to destroy_user_session_path, method: :delete, class: "logged-in-button" do %>
          <i class="fas fa-sign-out-alt"></i>
        <% end %>
      </div>
    <% when 'show' %>
      <div class="flex-end">
        <%= link_to '-Edit', edit_article_path, class: 'logged-in-button' %>
        <%= link_to '-Edit HTML', htmledit_article_path, class: 'logged-in-button' %>
        <%= link_to destroy_user_session_path, method: :delete, class: "logged-in-button" do %>
          <i class="fas fa-sign-out-alt"></i>
        <% end %>
      </div>
    <% else %>
      <div class="flex-end">
        <%= link_to "+Journal", new_update_path, class: "logged-in-button" %>
        <%= link_to "+People", new_profile_path, class: "logged-in-button" %>
        <%= link_to "+Insight", new_opinion_path, class: "logged-in-button" %>
        <%= link_to "+Video", new_video_path, class: "logged-in-button" %>
        <%= link_to "+Podcast", new_podcast_path, class: "logged-in-button" %>
        <%= link_to "+Dispatch", new_dispatch_path, class: "logged-in-button" %>
        <%= link_to "+Event", new_event_path, class: "logged-in-button" %>
        <%= link_to "+Space", new_space_path, class: "logged-in-button" %>
      </div>
      <div class="flex-end">
        <%= link_to "+Contributor", new_contributor_path, class: "logged-in-button" %>
        <%= link_to "+Photographer", new_photographer_path, class: "logged-in-button" %>
        <%= link_to "+Photo", new_photo_path, class: "logged-in-button" %>
      </div>
      <div class="flex-end">
        <%= link_to 'Contributors List', contributors_path, class: 'logged-in-button' %>
        <%= link_to destroy_user_session_path, method: :delete, class: "logged-in-button" do %>
          <i class="fas fa-sign-out-alt"></i>
        <% end %>
      </div>
    <% end %>

  </div>
</div>

app/views/shared/_mailchimp.html.erb
<div id="mc_embed_signup">
  <form action="https://systems-souls-society.us17.list-manage.com/subscribe/post?u=03daa88c3075ee5b17c8a7ce6&amp;id=f3b5021c84" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
      <div class="mc-field-group">
        <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" placeholder="your email address" required>
      </div>

      <div class="mc-field-group hidden">
        <label for="mce-FNAME">First Name </label>
        <input type="text" value="" name="FNAME" class="" id="mce-FNAME">
      </div>

      <div class="mc-field-group hidden">
        <label for="mce-LNAME">Last Name </label>
        <input type="text" value="" name="LNAME" class="" id="mce-LNAME">
      </div>

      <div id="mce-responses" class="clear hidden">
        <div class="response" id="mce-error-response" style="display:none"></div>
        <div class="response" id="mce-success-response" style="display:none"></div>
      </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->

      <div style="position: absolute; left: -5000px;" aria-hidden="true">
        <input type="text" name="b_03daa88c3075ee5b17c8a7ce6_f3b5021c84" tabindex="-1" value="">
      </div>

      <div class="clear">
        <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
      </div>
    </div>
  </form>
</div>



<!--End mc_embed_signup-->

app/views/shared/_mediacard.html.erb
<div class="card-container">
  <% if user_signed_in? %>
    <div class="logged-in-card">
      <h3 class="admin">
        <%= link_to('edit', edit_article_path(article)) %>
      </h3>
      <h3>
        <%= link_to('unpublish', publish_article_path(article)) if article.published %>
        <%= link_to('publish', publish_article_path(article)) unless article.published %>
      </h3>
      <h3>
        <%= link_to('delete', delete_article_path(article)) %>
      </h3>
    </div>
  <% end %>

  <% if article.url.include? 'youtube' %>
    <%= link_to article_path(article) do %>
      <%= content_tag :div, class: published?(article) do %>
        <div class="mediacard-img" style="background-image: url('<%= article.photo %>')">
          <div class="card-tag tag"><%= article.tag %></div>
        </div>
        <div class="card-text small">
          <h3 class="card-headline">
            <%= "#{article.contributor&.name}: " if article.category == "opinion" %><%= article.headline %>
          </h3>
          <h4 class="card-subhead"><%= article.subhead %></h4>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <%= link_to article.url, target: '_blank' do %>
      <%= content_tag :div, class: published?(article) do %>
        <div class="mediacard-img" style="background-image: url('<%= article.photo %>')">
          <div class="card-tag tag"><%= article.tag %></div>
        </div>
        <div class="card-text small">
          <h3 class="card-headline">
            <%= "#{article.contributor&.name}: " if article.category == "opinion" %><%= article.headline %>
          </h3>
          <h4 class="card-subhead"><%= article.subhead %></h4>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/shared/_tagbar.html.erb
<div class="tagbar-container hidden-xs hidden-sm">
  <div class="tagbar">
    <div class="hidden-xs hidden-sm">
      <%= link_to "All", {controller: controller_name, action: :index}, {class: "tagbar-link blank"} %>
      <% Article.where(category: @category).where(published: true).where(deleted: false).pluck(:tag).uniq(&:downcase).each do |tag| %>
        <%= link_to tag, {controller: controller_name, action: :index, tag: tag}, class: current_tag?(tag) %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_updatecard.erb
<div class="card-container">
  <%= link_to update_path(article) do %>
    <%= content_tag :div, class: updates_published?(article) do %>
      <div class="updates-card-content">
        <h1 class='updates-card-head center'><%= article.headline %></h1>
        <h2 class='updates-card-subhead center'><%= article.subhead %></h2>
        <div class="updates-center">
          <div class="updates-sharing">
            <%= link_to "http://twitter.com/share?text=#{article.headline}&url=#{request.original_url}" do %>
              <i class="social fab fa-twitter"></i>
            <% end %>
            <%= link_to "http://www.facebook.com/sharer.php?u=#{request.original_url}/&t=#{article.headline}" do %>
              <i class="social fab fa-facebook-f"></i>
            <% end %>
            <%= link_to "https://www.linkedin.com/shareArticle?mini=true&url=#{request.original_url}&title=#{article.headline}" do %>
              <i class="social fab fa-linkedin-in"></i>
            <% end %>
          </div>
          <div class="updates-bar"><hr></div>
          <div class="updates-date"><%= article.published_at %></div>
        </div>
        <%= article.body.truncate(500, separator: '</p>').html_safe %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_updatecard.html.erb
<div class="card-container">
  <% if user_signed_in? %>
    <div class="logged-in-card">
      <h3 class="admin">
        <%= link_to('edit', edit_article_path(article)) %>
      </h3>
      <h3>
        <%= link_to('unpublish', publish_article_path(article)) if article.published %>
        <%= link_to('publish', publish_article_path(article)) unless article.published %>
      </h3>
      <h3>
        <%= link_to('delete', delete_article_path(article)) %>
      </h3>
    </div>
  <% end %>

  <%= link_to update_path(article) do %>
    <%= content_tag :div, class: updates_published?(article) do %>
      <div class="updates-card-content">
        <h1 class='updates-card-head center'><%= article.headline %></h1>
        <h2 class='updates-card-subhead center'><%= article.subhead %></h2>
        <div class="updates-center">
          <div class="updates-sharing">
            <%= link_to "http://twitter.com/share?text=#{article.headline}&url=#{request.original_url}" do %>
            <i class="social fab fa-twitter"></i>
            <% end %>
            <%= link_to "http://www.facebook.com/sharer.php?u=#{request.original_url}/&t=#{article.headline}" do %>
            <i class="social fab fa-facebook-f"></i>
            <% end %>
            <%= link_to "https://www.linkedin.com/shareArticle?mini=true&url=#{request.original_url}&title=#{article.headline}" do %>
            <i class="social fab fa-linkedin-in"></i>
            <% end %>
          </div>
          <% unless article.published_at.nil? %>
            <div class="updates-bar"><hr></div>
            <%= link_to update_path(article), class: 'updates-date' do %>
              <%= article.published_at.strftime("%-d.%-m.%Y") %>
            <% end %>
          <% end %>
        </div>
        <%= link_to update_path(article), class: 'updates-snippet' do %>
          <% articleSnippet = article.body.truncate(500, separator: '</div>') %>
          <%= sanitize articleSnippet, tags: %w(br em b i p span),
    attributes: %w(width height alt cite datetime title class name xml:lang abbr type) %>
        <% end %>
        <%= link_to 'Read more', update_path(article), class: 'updates-more' %>
      </div>
    <% end %>
  <% end %>
</div>